### ISSUE TITLE
need help with this

### ISSUE THREAD

**Issue by deanm1278** [adafruit/pxt-seesaw#6]
Hey this is great thanks for doing this!
I've been trying to get this to deploy but I'm having problems. 

running pxt deploy I get this error:
```
C:\Users\deanm\Documents\dev_stuff\pxt-seesaw>pxt deploy
Could not determine target's pxt-core location, falling back to default: C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core
Using target adafruit with build engine codal
  target: v1.1.14 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-adafruit
  pxt-core: v3.12.17 C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core
HF2: Connected; msgSize 320B; flash 256kB; bootloader mode
HF2: Board-ID: SAMD21G18A-CPlay-v0 v1.26.0 fSFHWRO
HF2: Starting flash (96kB).
HF2: Flashing done at 41 kB/s in 2325ms (reset 0ms). Resetting.
HF2: recv error: could not read from HID device
```
and the device doesn't seem to do anything.
I can get it to work if I use the extension in makecode or if I serve makecode locally, but there are things that don't work I was going to try to fix.

is there another step to deploying that I'm missing?

Also, did you autogenerate this code from the cirpy library? there was a lot that just changed and if you have some way to regenerate the code that would be helpful.

Thanks!
-Dean

**Comment by deanm1278** [comment]
hey @pelikhan circuit python stuff is pretty much done so were ready to work on this. Please let me know if you can help me get a build going when you have a minute :)

**Comment by pelikhan** [comment]
There isn't anything specific about the deployment. It seems that it managed to start deploying. @mmoskal any idea?

Yes I did regenerate the code from the circuitplayground python library. Our generate does most of the work, but I had to update the naming conventions. I will add instructions in the README on how to do it.

**Comment by pelikhan** [comment]
@deanm1278 you probably want to keep this package "seesaw" only and actually create a new repo for the crickit.

**Comment by pelikhan** [comment]
In a nutshell, you want to run [pyconv](https://makecode.com/cli/pyconv) from this repo folder:

```
pxt pyconv SEESAWFOLDER
```

It will generate new .ts files that you can to merge in. The converter does not convert the naming conventions yet and gets the I2CDevice wrong -- aside from there, it's pretty much as is.
If you need to add block comments annotations, we can generate sperate .d.ts files so that they don't get overriden each time we regenerate. Ping me if you need help getting started.

**Comment by deanm1278** [comment]
ok great I'll check out the pyconv stuff, thanks!
do you think you or @mmoskal could be in discord tomorrow or wednesday between 10am and 6pm EST to help quick with the deploy process.
I can test and/or fix whatever once I have that set up but am kinda stuck currently.

**Comment by mmoskal** [comment]
The message from HID deploy is actually normal - the device resets and the read operation fails. You also should be able to just run `pxt build` and then copy `built/binary.hex` to `CPLAYBOOT`

**Comment by deanm1278** [comment]
thanks for the quick reply. this is the message it gives when I build:
```
C:\Users\deanm\Documents\dev_stuff\pxt-seesaw>pxt build
Could not determine target's pxt-core location, falling back to default: C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core
Using target adafruit with build engine codal
  target: v1.1.14 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-adafruit
  pxt-core: v3.12.17 C:\Users\deanm\Documents\dev_stuff\pxt-adafruit\node_modules\pxt-core
```

Then when I load the created uf2 file onto the circuitplayground (I assume that's the board it's building for? not sure how to check) it does nothing.
If I build and then drag the downloaded uf2 from makecode beta (or the locally running makecode server) the board boots and starts sending i2c commands. Do I need to set or change the board it's building for somewhere?

**Comment by pelikhan** [comment]
How do we connect on discord?
To target another board, you'll need to pxt-maker. It's the same prodecure as adafruit but there are other boards available like the Metro M0, etc..

**Comment by deanm1278** [comment]
ok so when I follow the instructions in the readme for this repo it's building for circuitplayground express, correct?
Here's one thing I forgot to mention. When I follow the instructions in the readme of this repo from a fresh clone it fails with this message:
```
C:\Users\deanm\Documents\dev_stuff\pxt-seesaw>pxt
Could not determine target's pxt-core location, falling back to default: C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core
Using target adafruit with build engine codal
  target: v1.1.15 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-adafruit
  pxt-core: v3.12.19 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core
running 'pxt deploy' (run 'pxt help' for usage)
Error: Package not installed: core, did you forget to run `pxt install`?
    at Object.userError (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core\built\pxt.js:98354:25)
    at Package.loadAsync (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core\built\pxt.js:104968:27)
    at C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core\built\pxt.js:105021:36
    at C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core\built\pxt.js:97926:77
    at Array.map (<anonymous>)
    at Object.mapStringMapAsync (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core\built\pxt.js:97926:51)
    at loadDepsRecursive (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core\built\pxt.js:105006:30)
    at C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core\built\pxt.js:105026:44
    at tryCatcher (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\bluebird\js\release\async.js:17:14)
USER ERROR: Package not installed: core, did you forget to run `pxt install`?
```
Then I run pxt install
```
C:\Users\deanm\Documents\dev_stuff\pxt-seesaw>pxt install
Could not determine target's pxt-core location, falling back to default: C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core
Using target adafruit with build engine codal
  target: v1.1.15 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-adafruit
  pxt-core: v3.12.19 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core
skipping download of local pkg: file:.
```
Then I re-run pxt
```
C:\Users\deanm\Documents\dev_stuff\pxt-seesaw>pxt
Could not determine target's pxt-core location, falling back to default: C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core
Using target adafruit with build engine codal
  target: v1.1.15 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-adafruit
  pxt-core: v3.12.19 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core
running 'pxt deploy' (run 'pxt help' for usage)
HF2: Connected; msgSize 320B; flash 256kB; bootloader mode
HF2: Board-ID: SAMD21G18A-CPlay-v0 v1.26.0 fSFHWRO
HF2: Starting flash (96kB).
HF2: skipping flash at: 0x2100 (88.25kB), 0x18200 (7.5kB)
HF2: Performing partial flash (0kB).
HF2: Flashing done at 25 kB/s in 10ms (reset 0ms). Resetting.
HF2: recv error: could not read from HID device
```
And then nothing happens.
Just to give you all the info in case I'm doing something wrong in that extra install step.

**Comment by mmoskal** [comment]
In this case it's building for CPX, since it's using `pxt-adafruit` package. In Maker you specify the board by referencing package (like `adafruit-metro-m0`, `bluebear-ble-nano` etc).

It might be some problem with your installation of ARM GCC. Did you try to gdb the code?

Otherwise, the `pxt install` stuff is normal

**Comment by deanm1278** [comment]
I'm only getting 3 files in my built directory:
binary.asm
binary.uf2
yotta.json

There doesn't seem to be an executable I can readily use with gdb. Is it supposed to be looking for an arm-none-eabi-gcc in my PATH? Is there some way to get verbose output on the pxt build so I can see what it's running or trying to run?

**Comment by pelikhan** [comment]
There is no C++ in this package so you should not require to run C++. It will assembly the resulting code into ``binary.uf2``

**Comment by deanm1278** [comment]
ok I'm not sure I'm following. Sorry, I'm still new to the whole pxt build system and I don't quite understand how it works just yet.
@mmoskal can you elaborate on how I can use gdb to debug what this package builds?

EDIT: for clarity, I'm familiar with using gdb, just not sure where the necessary files are in this build context. The pxt build output doesn't seem to show any compilation or linking against any precompiled core. If there are any docs you could point me to on how the pxt build process works that would also be very helpful.

**Comment by pelikhan** [comment]
Are you still stuck with this?

**Comment by ladyada** [comment]
dean's out for a bit, will be back in a week or so and jump back into it :)

**Comment by deanm1278** [comment]
hi @pelikhan I'm back in the office now. Yes unfortunately it still will not run and I cannot get any debug output other than this to figure out where it may be going wrong:
```
C:\Users\deanm\Documents\dev_stuff\pxt-seesaw>pxt build
Using target adafruit with build engine codal
  target: v1.1.19 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-adafruit
  pxt-core: v3.15.6 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-adafruit\node_modules\pxt-core
```
any help or info would be greatly appreciated.

Here's what the board does: When I plug it in it comes up as CPLAYBOOT mass storage device (this is normal). Then when I hit reset the onboard LEDs all stay green and the board comes up in Device Manager as "PXT Device", but there is no activity on the I2C bus.

When I compile the same code on makecode.adafruit.com/beta and hit reset the onboard LEDs all turn off, board comes up in Device Manager as "PXT Device" and there is activity on the I2C bus.

**Comment by pelikhan** [comment]
@deanm1278 i'm out of the office today, and I think @mmoskal is oof too. @abchatra can you take over?

**Comment by ladyada** [comment]
@abchatra @pelikhan @mmoskal  hiya are you able to compile and deploy the code in this repo? we haven't made any progress with our limited poking

**Comment by pelikhan** [comment]
I received the CRIKIT yesterday! I'll take a stab at this today.

**Comment by ladyada** [comment]
huzzah thanks! i think the first pxt is the toughest :D

**Comment by deanm1278** [comment]
ok I've gotten a build to work by creating a UF2 on makecode.adafruit.com/beta and then creating a new folder and doing:
```
$ pxt target adafruit
$ pxt extract circuitplayground-Untitled.uf2
$ cd Untitled
$ pxt deploy
```
for now I'll make my changes to the local seesaw.ts file that was created, copy them into my local copy of this repo and then PR to this repo.

**Comment by pelikhan** [comment]
Do you want to run the python converter first to pick all the updates? Where do you want to chat about this?

_____________________________

**Comment by deanm1278** [comment]
yes I'm gonna run the python converter now. I'll let you know how it goes and then we can try chatting in Discord if I need any more info.

**Comment by pelikhan** [comment]
Working on a fix for the CLI

_____________________________

**Comment by deanm1278** [comment]
a fix for the pyconv CLI you mean? This is the error I'm getting running pyconv:
```
C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\Untitled>pxt pyconv adafruit_seesaw
Using target adafruit with build engine codal
  target: v1.1.19 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-adafruit
  pxt-core: v3.15.6 C:\Users\deanm\Documents\dev_stuff\pxt-seesaw\node_modules\pxt-core
[run] py
INTERNAL ERROR: Error: spawn py ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by pelikhan** [comment]
I am on discord now, how do we setup a chat?

**Comment by deanm1278** [comment]
what's your tag number?
should have a pound sign in front of it (#)

**Comment by pelikhan** [comment]
#9234

**Comment by deanm1278** [comment]
I guess we have to be on the same server? try this link: https://discord.gg/BwHm6J

**Comment by ladyada** [comment]
we have a server already at adafruit! http://adafru.it/discord

**Comment by deanm1278** [comment]
closing since we've got a build system going. Thanks!
